eureka:
  client:
    service-url:
      #      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: clientname
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fxf3237221
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
env:
  dev
girl:
  name: lili
  age: 20
